Repository codeit-6th-part3-7team/7team-next-project, pull requests merged in 2024-06, with the labels that each got.

#4 :sparkles: [Add new action] 1개 이상의 approve가 있어야 PR이 머지될 수 있도록 함
  .github/workflows/require-approval.yaml
Labels: Priority: High 🔥, Type: Feature :sparkles:

#5 :rotating_light: Require Approval action 수정
  .github/workflows/require-approval.yaml
Labels: Priority: High 🔥, Type: Bug :bug:

#7 📚 install ui library
  package-lock.json
  package.json
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#9 라이브러리 인스톨, 테일윈드 커스텀 수정 부분 메인으로 머지
  package-lock.json
  package.json
  pages/index.tsx
  tailwind.config.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#11 Feat/header
  .eslintrc.js
  .husky/pre-commit
  .prettierrc.js
  pages/_app.tsx
  pages/index.tsx
  public/assets/ic_burger.svg
  public/assets/img_logo.webp
  src/components/Header.tsx
  src/styles/globals.css
  tailwind.config.ts
  tsconfig.json
Labels: Type: Feature :sparkles:

#12 📝 api 호출함수 작성 및 테스트
  .husky/pre-commit
  .vscode/settings.json
  package-lock.json
  package.json
  pages/wiki/[id].tsx
  src/apis/axios.ts
  src/types/ProfileResponse.d.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#14 Feat/회원가입 폼 유효성 검사 기능 구현
  .eslintrc.js
  .husky/pre-commit
  .prettierrc.js
  package-lock.json
  package.json
  pages/signup.tsx
  src/styles/globals.css
  tsconfig.json
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#16 Feat/kan 22 setup api(Add extention and settings for annotation)
  .vscode/settings.json
  pages/wiki/[id].tsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#15 fix: crlf 오류, Parsing 오류 해결 및 lint 설정 변경
  .eslintrc.js
  .husky/pre-commit
  .prettierrc.js
  package.json
  pages/index.tsx
  tsconfig.json
Labels: Priority: Medium :bookmark:, Type: Bug :bug:

#18 [kan-38] 퍼블리싱-기본 ui 작성
  .prettierrc.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/wiki/[id].tsx
  postcss.config.mjs
  public/ic_copy_link.svg
  public/img_temp_profile.png
  src/apis/.empty
  src/components/.empty
  src/components/ProfileCard.tsx
  src/styles/globals.css
  src/styles/theme.ts
  src/types/ProfileResponse.d.ts
  tailwind.config.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#20 [KAN-3] Landing Page UI 개발
  .prettierrc.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  public/assets/img_landing_01.webp
  public/assets/img_landing_02.webp
  public/assets/img_landing_03.webp
  public/assets/img_landing_04.webp
  public/assets/img_landing_05.webp
  public/assets/img_landing_06.webp
  public/assets/img_landing_07.webp
  public/assets/img_landing_08.webp
  public/assets/img_landing_09.webp
  public/assets/img_landing_10.webp
  src/components/Header.tsx
  src/styles/globals.css
  src/styles/theme.ts
  tailwind.config.ts
  tsconfig.json
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#21 [kan-23] 프로필 카드
  .vscode/settings.json
  pages/wiki/[id].tsx
  public/ic_profile_skeleton.webp
  public/img_temp_profile.png
  src/components/ProfileCard.tsx
  src/types/ProfileResponse.d.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#24 Feat/wiki list UI
  package-lock.json
  package.json
  pages/_app.tsx
  pages/wiki/wikiList.tsx
  public/ic_image_null.svg
  src/apis/axios.ts
  src/components/UserCard.tsx
  src/styles/globals.css
  src/types/wikiListTypes.d.ts
  tailwind.config.ts
  tsconfig.json
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#25 Feat/회원가입 기능 구현 및 mantine ui 적용
  .env
  .eslintrc.js
  .prettierrc.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/signup.tsx
  src/apis/axios.ts
  src/schema/signup.ts
  src/styles/globals.css
  src/styles/theme.ts
  src/types/type.ts
  tailwind.config.ts
Labels: Priority: High 🔥, Type: Feature :sparkles:

#30 Feat/로그인 폼 및 기능 구현
  .env
  .eslintrc.js
  .husky/pre-commit
  .prettierrc.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/login.tsx
  pages/signup.tsx
  src/apis/axios.ts
  src/schema/userFormSchema.ts
  src/styles/globals.css
  src/styles/theme.ts
  src/types/userFormData.ts
  tailwind.config.ts
  tsconfig.json
Labels: Priority: High 🔥, Type: Feature :sparkles:

#31 [kan 26] 위키 수정 인증 모달, 인증인가
  pages/_app.tsx
  pages/wiki/[id].tsx
  public/ic_lock.webp
  src/apis/authEditWiki.ts
  src/apis/axios.ts
  src/components/EditWikiAuthModal.tsx
  src/components/ProfileCard.tsx
  src/types/ProfileResponse.ts
Labels: Priority: High 🔥, Type: Feature :sparkles:

#29 에디터 UI 및 기능 구현
  .eslintrc.js
  .husky/pre-commit
  .prettierrc.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/addboard.tsx
  public/assets/ic_Alignment_center.svg
  public/assets/ic_Alignment_left.svg
  public/assets/ic_Alignment_right.svg
  public/assets/ic_Bullet.svg
  public/assets/ic_bold.svg
  public/assets/ic_camera.svg
  public/assets/ic_coloring.svg
  public/assets/ic_image.svg
  public/assets/ic_italic.svg
  public/assets/ic_numbering.svg
  public/assets/ic_underline.svg
  src/components/FileInput.tsx
  src/components/Menubar.tsx
  src/components/WriteBoard.tsx
  src/styles/editor.css
  src/styles/globals.css
  src/styles/theme.ts
  tailwind.config.ts
  tsconfig.json
Labels: Priority: High 🔥, Type: Feature :sparkles:

#28 Feat/search UI
  .vscode/settings.json
  pages/wiki/[id].tsx
  pages/wiki/wikiList.tsx
  public/favicon.ico
  public/ic_search.svg
  public/next.svg
  public/vercel.svg
  src/components/UserCard.tsx
  src/types/ProfileResponse.ts
  src/types/wikiListTypes.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#26 [KAN-14] post page UI
  .eslintrc.js
  .husky/pre-commit
  .prettierrc.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/hello.ts
  pages/boards.tsx
  pages/index.tsx
  public/assets/ic_bottom_arrow.svg
  public/assets/ic_burger.svg
  public/assets/ic_heart.svg
  public/assets/ic_left_arrow.svg
  public/assets/ic_right_arrow.svg
  public/assets/ic_search.svg
  public/assets/ic_up_arrow.svg
  public/assets/img_card_section.png
  public/assets/img_logo.webp
  public/favicon.ico
  public/next.svg
  public/vercel.svg
  src/apis/axios.ts
  src/components/boards/BestPost.tsx
  src/components/boards/Pagination.tsx
  src/components/boards/PostListTable.tsx
  src/components/boards/SearchBar.tsx
  src/components/boards/SortDropdown.tsx
  src/styles/globals.css
  src/types/boardTypes.ts
  src/utils/formatDate.ts
  tailwind.config.ts
  tsconfig.json
Labels: Priority: High 🔥, Type: Feature :sparkles:

#35 [KAN-42] 게시판 글 작성/수정 api 연결
  next.config.mjs
  package-lock.json
  package.json
  pages/addboard.tsx
  pages/boards/[id].tsx
  pages/boards/[id]/edit.tsx
  src/apis/axios.ts
  src/components/FileInput.tsx
  src/components/Menubar.tsx
  src/components/WriteBoard.tsx
  tailwind.config.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#37 [KAN-48] tailwind axios setting for every companions
  .husky/pre-commit
  .vscode/settings.json
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  src/apis/.empty
  src/apis/axios.ts
  src/styles/globals.css
  src/styles/theme.ts
  tailwind.config.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#36 [KAN-36] pagination UI
  pages/wiki/wikiList.tsx
  public/ic_left_arrow.svg
  public/ic_right_arrow.svg
  public/img_no_search.webp
  src/components/Pagination.tsx
  src/components/UserCard.tsx
  src/types/wikiListTypes.ts
  tailwind.config.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#23 [KAN-1] 에픽 머지 PR
  .eslintrc.js
  .husky/pre-commit
  .prettierrc.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  public/assets/ic_burger.svg
  public/assets/img_landing_01.webp
  public/assets/img_landing_02.webp
  public/assets/img_landing_03.webp
  public/assets/img_landing_04.webp
  public/assets/img_landing_05.webp
  public/assets/img_landing_06.webp
  public/assets/img_landing_07.webp
  public/assets/img_landing_08.webp
  public/assets/img_landing_09.webp
  public/assets/img_landing_10.webp
  public/assets/img_logo.webp
  src/components/Header.tsx
  src/styles/globals.css
  tsconfig.json
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#33 [KAN-39] 세션인증 구현
  next.config.mjs
  pages/_app.tsx
  pages/index.tsx
  pages/wiki/[id].tsx
  src/apis/authEditWiki.ts
  src/apis/axios.ts
  src/apis/checkWikiStatus.ts
  src/components/EditWikiAuthModal.tsx
  src/components/ProfileCard.tsx
  src/styles/theme.ts
  tailwind.config.ts
Labels: Priority: High 🔥, Type: Feature :sparkles:

#39 [KAN-48] tailwind 폰트, 반응형 브레이크포인트 설정
  src/styles/theme.ts
  tailwind.config.ts
Labels: Priority: High 🔥, Type: Feature :sparkles:

#40 [KAN-49] lint 설정 오류 수정, lint오류 수정
  .eslintrc.js
  .husky/pre-commit
  .prettierrc.js
  .vscode/settings.json
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/wiki/[id].tsx
  src/apis/authEditWiki.ts
  src/apis/checkWikiStatus.ts
  src/components/EditWikiAuthModal.tsx
  src/components/ProfileCard.tsx
  src/styles/theme.ts
Labels: Priority: High 🔥, Type: Refactor :recycle:

#42 Feat/로그인 & 회원가입시 Header 프로필 전환 구현
  .prettierrc.js
  .vscode/settings.json
  next.config.mjs
  pages/_app.tsx
  pages/index.tsx
  pages/login.tsx
  pages/login/index.tsx
  pages/signup.tsx
  pages/signup/index.tsx
  public/assets/ic_burger.svg
  public/assets/ic_profile.svg
  public/assets/img_landing_01.webp
  public/assets/img_landing_02.webp
  public/assets/img_landing_03.webp
  public/assets/img_landing_04.webp
  public/assets/img_landing_05.webp
  public/assets/img_landing_06.webp
  public/assets/img_landing_07.webp
  public/assets/img_landing_08.webp
  public/assets/img_landing_09.webp
  public/assets/img_landing_10.webp
  public/assets/img_logo.webp
  src/apis/.empty
  src/components/Header.tsx
  src/components/layout.tsx
  src/schema/signup.ts
  src/styles/globals.css
  src/styles/theme.ts
  src/types/type.ts
  src/types/userFormData.ts
  tailwind.config.ts
  tsconfig.json
Labels: Priority: High 🔥, Type: Feature :sparkles:

#44 [setting] label 연관된 input 찾도록 규칙 지정
  .eslintrc.js
  .gitignore
Labels: Type: Feature :sparkles:

#43 [KAN-45]my wiki page 반응형, develop 변경사항 머지
  .eslintrc.js
  .prettierrc.js
  pages/_app.tsx
  pages/index.tsx
  pages/wiki/[id].tsx
  public/assets/ic_burger.svg
  public/assets/img_landing_01.webp
  public/assets/img_landing_02.webp
  public/assets/img_landing_03.webp
  public/assets/img_landing_04.webp
  public/assets/img_landing_05.webp
  public/assets/img_landing_06.webp
  public/assets/img_landing_07.webp
  public/assets/img_landing_08.webp
  public/assets/img_landing_09.webp
  public/assets/img_landing_10.webp
  public/assets/img_logo.webp
  public/ic_chevron.webp
  src/apis/authEditWiki.ts
  src/apis/checkWikiStatus.ts
  src/components/EditWikiAuthModal.tsx
  src/components/Header.tsx
  src/components/ProfileCard.tsx
  src/styles/globals.css
  src/styles/theme.ts
  tailwind.config.ts
  tsconfig.json
Labels: Priority: High 🔥, Type: Improve UX :arrow_up:

#41 Feat/wiki list UI
  pages/_app.tsx
  pages/wiki/[id].tsx
  pages/wiki/wikiList.tsx
  public/ic_copy.svg
  src/components/SearchFrom.tsx
  src/components/UserCard.tsx
  src/styles/globals.css
  src/types/ProfileResponse.ts
  src/types/wikiListTypes.ts
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:
