Repository codeit-6th-part3-7team/7team-next-project, pull requests merged in 2024-07, with the labels that each got.

#51 [KAN-1] 랜딩페이지 머지요청 (디자인 시안에 맞게 조금 더 수정)
  .vscode/settings.json
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  pages/wiki/[id].tsx
  postcss.config.mjs
  public/ic_chevron.webp
  public/ic_copy_link.svg
  public/ic_lock.webp
  public/ic_profile_skeleton.webp
  src/apis/.empty
  src/apis/authEditWiki.ts
  src/apis/axios.ts
  src/apis/checkWikiStatus.ts
  src/components/.empty
  src/components/EditWikiAuthModal.tsx
  src/components/Header.tsx
  src/components/ProfileCard.tsx
  src/styles/globals.css
  src/styles/theme.ts
  src/types/ProfileResponse.ts
  tailwind.config.ts
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#49 [merge] my wiki page 머지 확인
  .eslintrc.js
  .gitignore
Labels: Priority: High 🔥, Type: Merge :truck:

#47 [Merge] epic/sign-up-page merge RR
  .eslintrc.js
  .gitignore
  pages/_app.tsx
  pages/login/index.tsx
  pages/signup/index.tsx
  src/components/layout.tsx
Labels: Priority: High 🔥, Type: Merge :truck:

#54 [KAN-42] 글 작성/수정 페이지 완료 : 이미지 선택하지 않았을 경우 초기화
  .env
  pages/boards/[id].tsx
  pages/boards/[id]/edit.tsx
  src/apis/axios.ts
  src/components/Menubar.tsx
Labels: Priority: Medium :bookmark:, Type: Improve UX :arrow_up:

#45 [KAN-50] 게시글 상세페이지 - 게시글 가져오기, 좋아요, 삭제하기 기능
  .env
  .eslintrc.js
  .husky/pre-commit
  .prettierrc.js
  .vscode/settings.json
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.tsx
  pages/boards/[id]/index.tsx
  pages/index.tsx
  public/assets/ic_bin.svg
  public/assets/ic_burger.svg
  public/assets/ic_heart.svg
  public/assets/ic_heart_on.svg
  public/assets/ic_pencil.svg
  public/assets/img_landing_01.webp
  public/assets/img_landing_02.webp
  public/assets/img_landing_03.webp
  public/assets/img_landing_04.webp
  public/assets/img_landing_05.webp
  public/assets/img_landing_06.webp
  public/assets/img_landing_07.webp
  public/assets/img_landing_08.webp
  public/assets/img_landing_09.webp
  public/assets/img_landing_10.webp
  public/assets/img_logo.webp
  src/apis/.empty
  src/apis/axios.ts
  src/components/Board.tsx
  src/components/Header.tsx
  src/styles/globals.css
  src/styles/theme.ts
  tailwind.config.ts
  tsconfig.json
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#57 [KAN-1] 랜딩페이지 머지요청입니다! 충돌 해결하여 다시올립니다 ㅠㅠ
  .env
  .eslintrc.js
  .gitignore
  package-lock.json
  package.json
  pages/index.tsx
  pages/login/index.tsx
  pages/signup/index.tsx
  public/assets/ic_profile.svg
  src/apis/axios.ts
  src/components/Header.tsx
  src/schema/userFormSchema.ts
  src/types/userFormData.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#52 [MERGE] 랜딩페이지 머지요청입니다!
  .vscode/settings.json
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  pages/wiki/[id].tsx
  postcss.config.mjs
  public/ic_chevron.webp
  public/ic_copy_link.svg
  public/ic_lock.webp
  public/ic_profile_skeleton.webp
  src/apis/authEditWiki.ts
  src/apis/checkWikiStatus.ts
  src/components/.empty
  src/components/EditWikiAuthModal.tsx
  src/components/Header.tsx
  src/components/ProfileCard.tsx
  src/styles/globals.css
  src/styles/theme.ts
  src/types/ProfileResponse.ts
Labels: Priority: High 🔥, Type: Epic :rocket:, Type: Merge :truck:

#53 [Merge] my wiki page merge develop
  .env
  pages/wiki/[id].tsx
Labels: Priority: High 🔥, Type: Epic :rocket:, Type: Merge :truck:

#59 [KAN-12] 머지 요청드립니다~
  .gitignore
  .vscode/settings.json
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/signup/index.tsx
  pages/wiki/[id].tsx
  postcss.config.mjs
  public/assets/ic_burger.svg
  public/assets/ic_profile.svg
  public/assets/img_landing_01.webp
  public/assets/img_landing_02.webp
  public/assets/img_landing_03.webp
  public/assets/img_landing_04.webp
  public/assets/img_landing_05.webp
  public/assets/img_landing_06.webp
  public/assets/img_landing_07.webp
  public/assets/img_landing_08.webp
  public/assets/img_landing_09.webp
  public/assets/img_landing_10.webp
  public/assets/img_logo.webp
  public/ic_chevron.webp
  public/ic_copy_link.svg
  public/ic_lock.webp
  public/ic_profile_skeleton.webp
  src/apis/.empty
  src/apis/authEditWiki.ts
  src/apis/axios.ts
  src/apis/checkWikiStatus.ts
  src/components/.empty
  src/components/EditWikiAuthModal.tsx
  src/components/Header.tsx
  src/components/ProfileCard.tsx
  src/schema/userFormSchema.ts
  src/styles/theme.ts
  src/types/ProfileResponse.ts
  src/types/userFormData.ts
  tailwind.config.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#64 [Merge] epic/account-setting-page update merge PR
  .eslintrc.js
  .gitignore
  .husky/pre-commit
  .prettierrc.js
  .vscode/settings.json
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/signup/index.tsx
  pages/wiki/[id].tsx
  postcss.config.mjs
  public/assets/ic_burger.svg
  public/assets/ic_profile.svg
  public/assets/img_landing_01.webp
  public/assets/img_landing_02.webp
  public/assets/img_landing_03.webp
  public/assets/img_landing_04.webp
  public/assets/img_landing_05.webp
  public/assets/img_landing_06.webp
  public/assets/img_landing_07.webp
  public/assets/img_landing_08.webp
  public/assets/img_landing_09.webp
  public/assets/img_landing_10.webp
  public/assets/img_logo.webp
  public/ic_chevron.webp
  public/ic_copy_link.svg
  public/ic_lock.webp
  public/ic_profile_skeleton.webp
  src/apis/.empty
  src/apis/authEditWiki.ts
  src/apis/axios.ts
  src/apis/checkWikiStatus.ts
  src/components/.empty
  src/components/EditWikiAuthModal.tsx
  src/components/Header.tsx
  src/components/ProfileCard.tsx
  src/schema/userFormSchema.ts
  src/styles/globals.css
  src/styles/theme.ts
  src/types/ProfileResponse.ts
  src/types/userFormData.ts
  tailwind.config.ts
  tsconfig.json
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#65 [KAN-9] wiki-list-page
  .eslintrc.js
  .gitignore
  .vscode/settings.json
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/signup/index.tsx
  pages/wiki/[id].tsx
  pages/wikilist/index.tsx
  postcss.config.mjs
  public/assets/ic_burger.svg
  public/assets/ic_profile.svg
  public/assets/img_landing_01.webp
  public/assets/img_landing_02.webp
  public/assets/img_landing_03.webp
  public/assets/img_landing_04.webp
  public/assets/img_landing_05.webp
  public/assets/img_landing_06.webp
  public/assets/img_landing_07.webp
  public/assets/img_landing_08.webp
  public/assets/img_landing_09.webp
  public/assets/img_landing_10.webp
  public/assets/img_logo.webp
  public/ic_chevron.webp
  public/ic_copy_link.svg
  public/ic_lock.webp
  public/ic_profile_skeleton.webp
  src/apis/.empty
  src/apis/authEditWiki.ts
  src/apis/axios.ts
  src/apis/checkWikiStatus.ts
  src/components/.empty
  src/components/EditWikiAuthModal.tsx
  src/components/Header.tsx
  src/components/Pagination.tsx
  src/components/ProfileCard.tsx
  src/components/UserCard.tsx
  src/schema/userFormSchema.ts
  src/styles/globals.css
  src/styles/theme.ts
  src/types/ProfileResponse.ts
  src/types/userFormData.ts
  tailwind.config.ts
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#62 [KAN-50] 게시글 상세페이지 게시글 부분 테스트 후 수정
  .gitignore
  .vscode/settings.json
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/boards/[id]/index.tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/signup/index.tsx
  pages/wiki/[id].tsx
  pages/wiki/index.tsx
  postcss.config.mjs
  public/assets/ic_profile.svg
  public/ic_chevron.webp
  public/ic_copy_link.svg
  public/ic_lock.webp
  public/ic_profile_skeleton.webp
  public/icons/ic_align_left.svg
  public/icons/ic_arrow_down.svg
  public/icons/ic_bold.svg
  public/icons/ic_bullet_list.svg
  public/icons/ic_expand.svg
  public/icons/ic_italic.svg
  public/icons/ic_link.svg
  public/icons/ic_number_list.svg
  public/icons/ic_picture.svg
  public/icons/ic_underline.svg
  public/icons/ic_video.svg
  src/apis/authEditWiki.ts
  src/apis/axios.ts
  src/apis/checkWikiStatus.ts
  src/components/.empty
  src/components/Board.tsx
  src/components/EditWikiAuthModal.tsx
  src/components/Header.tsx
  src/components/ProfileCard.tsx
  src/components/WikiEditor.tsx
  src/components/WikiEditorButton.tsx
  src/components/WikiEditorMenu.tsx
  src/schema/userFormSchema.ts
  src/styles/globals.css
  src/styles/theme.ts
  src/types/ProfileResponse.ts
  src/types/userFormData.ts
  tailwind.config.ts
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#66 Feat/비밀번호 변경 폼 및 위키생성 폼 구현
  pages/login/index.tsx
  pages/mypage/index.tsx
  src/components/ChangePasswordForm.tsx
  src/components/CreateWikiForm.tsx
  src/components/Header.tsx
  src/schema/userFormSchema.ts
  src/types/userFormData.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#70 [KAN-44]위키 수정 컴포넌트 작성
  pages/wiki/[id].tsx
  pages/wiki/[id]/index.tsx
  pages/wiki/index.tsx
  src/components/EditWikiAuthModal.tsx
  src/components/ProfileCardEditor.tsx
  src/components/WikiEditor.tsx
  src/components/WikiEditorMenu.tsx
  src/types/ProfileResponse.ts
Labels: Priority: High 🔥, Type: Feature :sparkles:

#69 [Refactor] wiki page
  pages/_document.tsx
  pages/wiki/[id].tsx
  pages/wikilist/index.tsx
  src/components/EditWikiAuthModal.tsx
  src/components/Pagination.tsx
  src/components/ProfileCard.tsx
  src/components/SearchFrom.tsx
  src/components/UserCard.tsx
Labels: Priority: Medium :bookmark:, Type: Doc :memo:

#61 [KAN-47] post page 반응형 구현 [추가 부분 재승인 요청]
  .env
  .prettierrc.js
  .vscode/settings.json
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.tsx
  pages/boards.tsx
  pages/index.tsx
  public/assets/img_landing_01.webp
  public/assets/img_landing_02.webp
  public/assets/img_landing_03.webp
  public/assets/img_landing_04.webp
  public/assets/img_landing_05.webp
  public/assets/img_landing_06.webp
  public/assets/img_landing_07.webp
  public/assets/img_landing_08.webp
  public/assets/img_landing_09.webp
  public/assets/img_landing_10.webp
  src/apis/.empty
  src/apis/axios.ts
  src/components/Header.tsx
  src/components/boards/BestPost.tsx
  src/components/boards/Pagination.tsx
  src/components/boards/PostListTable.tsx
  src/components/boards/SearchBar.tsx
  src/components/boards/SortDropdown.tsx
  src/styles/globals.css
  src/styles/theme.ts
  tailwind.config.ts
Labels: Priority: High 🔥

#71 [Merge] develop wiki list page
  .prettierrc.js
  pages/wiki/[id].tsx
  pages/wikilist/index.tsx
  src/apis/axios.ts
  src/components/Pagination.tsx
  src/components/UserCard.tsx
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#72 [KAN-58]develop PR from post-list-page
  .eslintrc.js
  .gitignore
  .vscode/settings.json
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/boards.tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/signup/index.tsx
  pages/wiki/[id].tsx
  postcss.config.mjs
  public/assets/ic_profile.svg
  public/ic_chevron.webp
  public/ic_copy_link.svg
  public/ic_lock.webp
  public/ic_profile_skeleton.webp
  src/apis/authEditWiki.ts
  src/apis/axios.ts
  src/apis/checkWikiStatus.ts
  src/components/.empty
  src/components/EditWikiAuthModal.tsx
  src/components/Header.tsx
  src/components/ProfileCard.tsx
  src/schema/userFormSchema.ts
  src/styles/globals.css
  src/styles/theme.ts
  src/types/ProfileResponse.ts
  src/types/userFormData.ts
  tailwind.config.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#68 [KAN-12] 게시글 작성/수정 페이지 리팩토링 (리뷰 반영)
  package-lock.json
  package.json
  pages/addboard.tsx
  pages/boards/[id]/edit.tsx
  src/components/FileInput.tsx
  src/components/Menubar.tsx
  src/components/WriteBoard.tsx
  src/styles/globals.css
Labels: Priority: High 🔥, Type: Refactor :recycle:

#77 [KAN-11] 게시글 상세페이지
  pages/boards/[id]/index.tsx
  public/assets/img_logo.svg
  src/components/Board.tsx
  src/components/Header.tsx
  src/components/Reply.tsx
  src/components/WriteReply.tsx
  src/styles/globals.css
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#75 [KAN-57] 위키수정페이지 에디터 메뉴바 기능구현, 반응형디자인 적용
  .prettierrc.js
  package-lock.json
  package.json
  pages/wiki/[id]/index.tsx
  postcss.config.mjs
  public/icons/ic_photo.svg
  src/components/HeadingsDropdown.tsx
  src/components/ProfileCard.tsx
  src/components/ProfileCardEditor.tsx
  src/components/SetLinkModal.tsx
  src/components/WikiEditor.tsx
  src/components/WikiEditorButton.tsx
  src/components/WikiEditorMenu.tsx
Labels: Priority: High 🔥, Type: Feature :sparkles:

#79 [KAN-11] 게시글 상세페이지
  pages/boards/[id]/index.tsx
  src/components/EditWikiAuthModal.tsx
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#80 Feat/위키 변경사항 알림 Dialog 구현
  public/assets/ic_alarm.svg
  src/components/Header.tsx
  src/components/WikiEditNotification.tsx
  src/types/NotificationResponse.ts
  src/utils/formatTimeAgo.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#81 [Merge] 위키 수정 페이지 Merge PR
  .prettierrc.js
  package-lock.json
  package.json
  pages/wiki/[id].tsx
  pages/wiki/[id]/index.tsx
  pages/wiki/index.tsx
  postcss.config.mjs
  public/icons/ic_align_left.svg
  public/icons/ic_arrow_down.svg
  public/icons/ic_bold.svg
  public/icons/ic_bullet_list.svg
  public/icons/ic_expand.svg
  public/icons/ic_italic.svg
  public/icons/ic_link.svg
  public/icons/ic_number_list.svg
  public/icons/ic_photo.svg
  public/icons/ic_picture.svg
  public/icons/ic_underline.svg
  public/icons/ic_video.svg
  src/components/EditWikiAuthModal.tsx
  src/components/Header.tsx
  src/components/HeadingsDropdown.tsx
  src/components/ProfileCard.tsx
  src/components/ProfileCardEditor.tsx
  src/components/SetLinkModal.tsx
  src/components/WikiEditor.tsx
  src/components/WikiEditorButton.tsx
  src/components/WikiEditorMenu.tsx
  src/styles/globals.css
  src/types/ProfileResponse.ts
  tailwind.config.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#85 [sd] 게시글 상세페이지 파일 분리
  package-lock.json
  package.json
  pages/boards/[id]/index.tsx
  public/assets/ic_bin.svg
  public/assets/ic_heart.svg
  public/assets/ic_heart_on.svg
  public/assets/ic_pencil.svg
  public/assets/img_logo.svg
  public/assets/user.svg
  src/components/Board.tsx
  src/components/Reply.tsx
  src/components/WriteReply.tsx
  src/styles/globals.css
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#86 [MERGE] 게시글 상세페이지 머지요청
  package-lock.json
  package.json
  pages/boards/[id]/index.tsx
  public/assets/ic_bin.svg
  public/assets/ic_heart.svg
  public/assets/ic_heart_on.svg
  public/assets/ic_pencil.svg
  public/assets/img_logo.svg
  public/assets/user.svg
  src/components/Board.tsx
  src/components/Reply.tsx
  src/components/WriteReply.tsx
  src/styles/globals.css
Labels: Priority: Medium :bookmark:, Type: Epic :rocket:, Type: Merge :truck:

#87 [s] 게시글 작성페이지 머지
  .prettierrc.js
  package-lock.json
  package.json
  pages/boards/[id]/index.tsx
  pages/wiki/[id].tsx
  pages/wiki/[id]/index.tsx
  pages/wiki/index.tsx
  postcss.config.mjs
  public/assets/ic_bin.svg
  public/assets/ic_heart.svg
  public/assets/ic_heart_on.svg
  public/assets/ic_pencil.svg
  public/assets/img_logo.svg
  public/assets/user.svg
  public/icons/ic_align_left.svg
  public/icons/ic_arrow_down.svg
  public/icons/ic_bold.svg
  public/icons/ic_bullet_list.svg
  public/icons/ic_expand.svg
  public/icons/ic_italic.svg
  public/icons/ic_link.svg
  public/icons/ic_number_list.svg
  public/icons/ic_photo.svg
  public/icons/ic_picture.svg
  public/icons/ic_underline.svg
  public/icons/ic_video.svg
  src/apis/axios.ts
  src/components/Board.tsx
  src/components/EditWikiAuthModal.tsx
  src/components/Header.tsx
  src/components/HeadingsDropdown.tsx
  src/components/ProfileCard.tsx
  src/components/ProfileCardEditor.tsx
  src/components/Reply.tsx
  src/components/SetLinkModal.tsx
  src/components/WikiEditor.tsx
  src/components/WikiEditorButton.tsx
  src/components/WikiEditorMenu.tsx
  src/components/WriteReply.tsx
  src/styles/globals.css
  src/styles/theme.ts
  src/types/ProfileResponse.ts
  tailwind.config.ts
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#76 [MERGE] 게시글 작성/수정 페이지 머지 요청드립니다.
  .env
  package-lock.json
  package.json
  pages/addboard.tsx
  pages/boards/[id]/edit.tsx
  public/assets/ic_Alignment_center.svg
  public/assets/ic_Alignment_left.svg
  public/assets/ic_Alignment_right.svg
  public/assets/ic_Bullet.svg
  public/assets/ic_bold.svg
  public/assets/ic_camera.svg
  public/assets/ic_coloring.svg
  public/assets/ic_image.svg
  public/assets/ic_italic.svg
  public/assets/ic_link.svg
  public/assets/ic_numbering.svg
  public/assets/ic_underline.svg
  src/apis/axios.ts
  src/components/EditWikiAuthModal.tsx
  src/components/FileInput.tsx
  src/components/Menubar.tsx
  src/components/WikiEditor.tsx
  src/components/WriteBoard.tsx
  src/styles/editor.css
  src/styles/globals.css
  src/styles/theme.ts
Labels: Priority: High 🔥, Type: Epic :rocket:, Type: Merge :truck:

#90 [KAN-58] 머지브랜치에서 에픽 포스트리스트페이지
  .prettierrc.js
  package-lock.json
  package.json
  pages/boards/[id]/index.tsx
  pages/boards/index.tsx
  pages/wiki/[id].tsx
  pages/wiki/[id]/index.tsx
  pages/wiki/index.tsx
  postcss.config.mjs
  public/assets/ic_bin.svg
  public/assets/ic_heart.svg
  public/assets/ic_heart_on.svg
  public/assets/ic_pencil.svg
  public/assets/img_logo.svg
  public/assets/user.svg
  public/ic_left_arrow.svg
  public/ic_right_arrow.svg
  public/icons/ic_align_left.svg
  public/icons/ic_arrow_down.svg
  public/icons/ic_bold.svg
  public/icons/ic_bullet_list.svg
  public/icons/ic_expand.svg
  public/icons/ic_italic.svg
  public/icons/ic_link.svg
  public/icons/ic_number_list.svg
  public/icons/ic_photo.svg
  public/icons/ic_picture.svg
  public/icons/ic_underline.svg
  public/icons/ic_video.svg
  src/components/Board.tsx
  src/components/EditWikiAuthModal.tsx
  src/components/HeadingsDropdown.tsx
  src/components/Pagination.tsx
  src/components/ProfileCard.tsx
  src/components/ProfileCardEditor.tsx
  src/components/Reply.tsx
  src/components/SetLinkModal.tsx
  src/components/WikiEditor.tsx
  src/components/WikiEditorButton.tsx
  src/components/WikiEditorMenu.tsx
  src/components/WriteReply.tsx
  src/components/boards/Pagination.tsx
  src/components/boards/SearchBar.tsx
  src/components/boards/SortDropdown.tsx
  src/styles/globals.css
  src/types/ProfileResponse.ts
  tailwind.config.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#73 [MERGE] 자유게시판 머지 요청드립니다
  .env
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/hello.ts
  pages/boards/index.tsx
  public/assets/ic_bottom_arrow.svg
  public/assets/ic_search.svg
  public/assets/ic_up_arrow.svg
  public/assets/img_card_section.png
  public/favicon.ico
  public/ic_left_arrow.svg
  public/ic_right_arrow.svg
  public/next.svg
  public/vercel.svg
  src/components/EditWikiAuthModal.tsx
  src/components/Pagination.tsx
  src/components/boards/BestPost.tsx
  src/components/boards/PostListTable.tsx
  src/components/boards/SearchBar.tsx
  src/components/boards/SortDropdown.tsx
  src/styles/globals.css
  src/types/boardTypes.ts
  src/utils/formatDate.ts
Labels: Priority: Medium :bookmark:, Type: Epic :rocket:, Type: Merge :truck:

#91 [Merge] epic/account-setting-page update
  .prettierrc.js
  package-lock.json
  package.json
  pages/wiki/[id].tsx
  pages/wiki/[id]/index.tsx
  pages/wiki/index.tsx
  postcss.config.mjs
  public/icons/ic_align_left.svg
  public/icons/ic_arrow_down.svg
  public/icons/ic_bold.svg
  public/icons/ic_bullet_list.svg
  public/icons/ic_expand.svg
  public/icons/ic_italic.svg
  public/icons/ic_link.svg
  public/icons/ic_number_list.svg
  public/icons/ic_photo.svg
  public/icons/ic_picture.svg
  public/icons/ic_underline.svg
  public/icons/ic_video.svg
  src/components/EditWikiAuthModal.tsx
  src/components/Header.tsx
  src/components/HeadingsDropdown.tsx
  src/components/ProfileCard.tsx
  src/components/ProfileCardEditor.tsx
  src/components/SetLinkModal.tsx
  src/components/WikiEditor.tsx
  src/components/WikiEditorButton.tsx
  src/components/WikiEditorMenu.tsx
  src/styles/globals.css
  src/types/ProfileResponse.ts
  tailwind.config.ts
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#92 fix: fix tailwind configuration in global css
  src/styles/globals.css
Labels: Priority: High 🔥

#93 [KAN-12] 게시글 작성/수정 페이지 머지요청
  .env
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/hello.ts
  pages/boards/index.tsx
  pages/login/index.tsx
  pages/signup/index.tsx
  public/assets/ic_bottom_arrow.svg
  public/assets/ic_search.svg
  public/assets/ic_up_arrow.svg
  public/assets/img_card_section.png
  public/favicon.ico
  public/ic_left_arrow.svg
  public/ic_right_arrow.svg
  public/next.svg
  public/vercel.svg
  src/apis/axios.ts
  src/components/Board.tsx
  src/components/Pagination.tsx
  src/components/WikiEditor.tsx
  src/components/boards/BestPost.tsx
  src/components/boards/PostListTable.tsx
  src/components/boards/SearchBar.tsx
  src/components/boards/SortDropdown.tsx
  src/styles/globals.css
  src/styles/theme.ts
  src/types/boardTypes.ts
  src/utils/formatDate.ts
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#95 [KAN-12] 게시글 상세페이지 머지요청
  src/styles/globals.css
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#96 [KAN-12] 게시글 작성/수정페이지 머지요청입니다~~
  src/styles/globals.css
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#97 [KAN-12] 게시글 작성/수정페이지 삭제모달 버튼 색상 수정
  src/components/Board.tsx
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#94 [MERGE] 게시판 작성/수정 페이지
  .env
  package-lock.json
  package.json
  pages/addboard.tsx
  pages/boards/[id]/edit.tsx
  pages/login/index.tsx
  pages/signup/index.tsx
  public/assets/ic_Alignment_center.svg
  public/assets/ic_Alignment_left.svg
  public/assets/ic_Alignment_right.svg
  public/assets/ic_Bullet.svg
  public/assets/ic_bold.svg
  public/assets/ic_camera.svg
  public/assets/ic_coloring.svg
  public/assets/ic_image.svg
  public/assets/ic_italic.svg
  public/assets/ic_link.svg
  public/assets/ic_numbering.svg
  public/assets/ic_underline.svg
  src/components/Board.tsx
  src/components/FileInput.tsx
  src/components/Menubar.tsx
  src/components/WriteBoard.tsx
  src/styles/editor.css
  src/styles/globals.css
Labels: Priority: Medium :bookmark:, Type: Epic :rocket:, Type: Merge :truck:

#98 [Merge] wiki list page
  pages/wiki/[id]/index.tsx
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#104 [Merge/Docs] wiki list end
  src/components/UserCard.tsx
Labels: Priority: High 🔥, Type: Doc :memo:, Type: Merge :truck:

#107 [Merge] epic/account-setting-page merge to develop PR
  package-lock.json
  package.json
  pages/boards/index.tsx
  pages/login/index.tsx
  pages/mypage/index.tsx
  public/assets/ic_alarm.svg
  src/components/ChangePasswordForm.tsx
  src/components/CreateWikiForm.tsx
  src/components/Header.tsx
  src/components/Reply.tsx
  src/components/SearchFrom.tsx
  src/components/UserCard.tsx
  src/components/WikiEditNotification.tsx
  src/schema/userFormSchema.ts
  src/types/NotificationResponse.ts
  src/types/userFormData.ts
  src/utils/formatTimeAgo.ts
  tailwind.config.ts
Labels: Priority: High 🔥, Type: Merge :truck:

#109 hotfix : 버튼 안보이는 문제 수정
  pages/boards/[id]/index.tsx
  pages/wiki/[id]/index.tsx
  src/components/WriteReply.tsx
Labels: Priority: Medium :bookmark:, Type: Doc :memo:

#112 [Refactor] kAN-61 wiki edit page refactoring
  .vscode/settings.json
  pages/wiki/[id]/index.tsx
  src/components/EditWikiAuthModal.tsx
  src/components/ProfileCardEditor.tsx
  src/components/SetLinkModal.tsx
Labels: Priority: High 🔥, Type: Merge :truck:

#113 [Refactor] [KAN-61] 위키 수정 권한 인증 부분 로직 개선
  pages/wiki/[id]/index.tsx
  src/apis/axios.ts
  src/apis/checkWikiStatus.ts
  src/components/EditWikiAuthModal.tsx
Labels: Priority: High 🔥, Type: Refactor :recycle:

#114 Refactor/위키수정 알림 내역 삭제 기능 수정
  pages/wiki/[id]/index.tsx
  src/components/ChangePasswordForm.tsx
  src/components/CreateWikiForm.tsx
  src/components/Header.tsx
  src/components/WikiEditNotification.tsx
Labels: Priority: High 🔥, Type: Refactor :recycle:

#115 FIX 버튼, 이름, 게시글 오류 수정
  src/components/EditWikiAuthModal.tsx
  src/components/HeadingsDropdown.tsx
  src/components/WikiEditorMenu.tsx
  src/components/boards/BestPost.tsx
Labels: Priority: High 🔥, Type: Bug :bug:

#117 [Merge] develop main
  src/components/UserCard.tsx
Labels: Priority: High 🔥, Type: Bug :bug:

#118 fix: 로그인 안했을 경우 오류 메시지 추가, feat: 자유게시판 댓글 무한스크롤 기능 추가
  package-lock.json
  package.json
  pages/boards/[id]/edit.tsx
  pages/boards/[id]/index.tsx
  src/components/Board.tsx
Labels: Priority: Medium :bookmark:
